In [1]:
import pandas as pd
import sqlite3

# load final churn decision data
sql_df = pd.read_csv("churn_retention_decisions.csv")

# create SQLite database
conn = sqlite3.connect("customer_analytics.db")

# create SQL table
sql_df.to_sql(
    name="churn_retention",
    con=conn,
    if_exists="replace",
    index=False
)

conn.close()

In [2]:
import sqlite3
import pandas as pd

# connect to database
conn = sqlite3.connect("customer_analytics.db")

# run SQL query
query = """
SELECT *
FROM churn_retention
LIMIT 10;
"""

sql_check_df = pd.read_sql(query, conn)
conn.close()

sql_check_df

,recency,frequency,monetary,actual_churn,churn_probability,high_risk,priority_score,retention_action
0,371,1,178.28,1,1.000000,1,178.279999,Discount Email / Push Notification
1,0,23,6849.15,0,0.001237,0,8.475451,No Action
2,232,11,3019.22,1,0.999928,1,3019.001230,Personal Call + Premium Offer
3,32,16,5969.93,0,0.010764,0,64.258827,No Action
4,24,2,514.56,0,0.006056,0,3.116008,No Action
5,206,5,1346.75,1,0.999538,1,1346.127232,Discount Email / Push Notification
6,420,2,370.45,1,1.000000,1,370.450000,Discount Email / Push Notification
7,372,1,488.16,1,1.000000,1,488.159998,Discount Email / Push Notification
8,395,2,24.35,1,1.000000,1,24.350000,Discount Email / Push Notification
9,30,3,949.25,0,0.009193,0,8.726611,No Action

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("customer_analytics.db")

query = """
SELECT 
    SUM(monetary) AS revenue_at_risk
FROM churn_retention
WHERE high_risk = 1;
"""

revenue_risk_df = pd.read_sql(query, conn)
conn.close()

revenue_risk_df

   revenue_at_risk
0       888549.873

In [4]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("customer_analytics.db")

query = """
SELECT 
    retention_action,
    COUNT(*) AS customer_count
FROM churn_retention
GROUP BY retention_action
ORDER BY customer_count DESC;
"""

action_dist_df = pd.read_sql(query, conn)
conn.close()

action_dist_df

                     retention_action  customer_count
0                           No Action             754
1  Discount Email / Push Notification             674
2       Personal Call + Premium Offer              42

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("customer_analytics.db")

query = """
SELECT
    recency,
    frequency,
    monetary,
    churn_probability,
    priority_score,
    retention_action
FROM churn_retention
WHERE high_risk = 1
ORDER BY priority_score DESC
LIMIT 20;
"""

top_customers_df = pd.read_sql(query, conn)
conn.close()

top_customers_df

,recency,frequency,monetary,churn_probability,priority_score,retention_action
0,325,12,77556.460,0.999999,77556.360595,Personal Call + Premium Offer
1,275,55,54943.650,0.999989,54943.059066,Personal Call + Premium Offer
2,234,3,44534.300,0.999715,44521.621928,Personal Call + Premium Offer
3,631,5,34095.260,1.000000,34095.260000,Personal Call + Premium Offer
4,162,33,16644.010,0.988830,16458.104024,Personal Call + Premium Offer
5,630,2,13916.340,1.000000,13916.340000,Personal Call + Premium Offer
6,437,1,11880.840,1.000000,11880.839999,Personal Call + Premium Offer
7,382,15,11123.350,1.000000,11123.349973,Personal Call + Premium Offer
8,564,1,10877.180,1.000000,10877.180000,Personal Call + Premium Offer
9,172,23,9962.110,0.994855,9910.858314,Personal Call + Premium Offer
10,205,18,9565.120,0.999458,9559.938062,Personal Call + Premium Offer
11,319,5,9443.040,1.000000,9443.037927,Personal Call + Premium Offer
12,280,11,9030.660,0.999997,9030.632362,Personal Call + Premium Offer
13,184,10,7793.510,0.997506,7774.074335,Personal Call + Premium Offer
14,147,13,6713.500,0.970000,6512.097802,Personal Call + Premium Offer
15,491,11,6251.260,1.000000,6251.260000,Personal Call + Premium Offer
16,410,12,5625.461,1.000000,5625.460998,Personal Call + Premium Offer
17,136,8,6017.060,0.934374,5622.184526,Personal Call + Premium Offer
18,128,11,6103.740,0.894280,5458.454595,Personal Call + Premium Offer
19,211,4,5164.880,0.999624,5162.940141,Personal Call + Premium Offer